# Numpy 

In [ ]:
lst=[1,2,3]
boto3, microsoftazuremgmt
sys os

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. It contains various features including these important ones:

A powerful N-dimensional array object

Sophisticated (broadcasting) functions

Tools for integrating C/C++ and Fortran code
Useful linear algebra, Fourier transform, and random number capabilities

# Operations that can be performed with NUMPY

1. Importing/Exporting
2. Creating an array
3. Inspect Property of an Array
4. Copying/Sorting/Reshaping
5. Adding/Removing Elements
6. Combining or Spliting
7. Indexing/Subseting/Slicing
8. Scalr Math
9. Vector Math
10. Statistics

# Key and Imports

arr | A NumPy Array object


You’ll also need to import numpy to get started:


import numpy as np

#### Importing/exporting
np.loadtxt('file.txt') | From a text file'

np.genfromtxt('file.csv',delimiter=',') | From a CSV file

np.savetxt('file.txt',arr,delimiter=' ') | Writes to a text file

np.savetxt('file.csv',arr,delimiter=',') | Writes to a CSV file

#### Creating Arrays (Generator function)
np.array([1,2,3]) | One dimensional array

np.array([(1,2,3),(4,5,6)]) | Two dimensional array

np.zeros(3) | 1D array of length 3 all values 0

np.ones((3,4)) | 3x4 array with all values 1

np.eye(5) | 5x5 array of 0 with 1 on diagonal (Identity matrix)

np.linspace(0,100,6) | Array of 6 evenly divided values from 0 to 100

np.arange(0,10,3) | Array of values from 0 to less than 10 with step 3 (eg [0,3,6,9])

np.full((2,3),8) | 2x3 array with all values 8

np.random.rand(4,5) | 4x5 array of random floats between 0–1

np.random.rand(6,7)*100 | 6x7 array of random floats between 0–100

np.random.randint(5,size=(2,3)) | 2x3 array with random ints between 0–4 


row*col

#### Inspecting Properties


arr.size | Returns number of elements in arr

arr.shape | Returns dimensions of arr (rows,columns)

arr.dtype | Returns type of elements in arr

arr.astype(dtype) | Convert arr elements to type dtype

arr.tolist() | Convert arr to a Python list

np.info(np.eye) | View documentation for np.eye

#### Copying/sorting/reshaping

np.copy(arr) | Copies arr to new memory

arr.view(dtype) | Creates view of arr elements with type dtype

arr.sort() | Sorts arr

arr.sort(axis=0) | Sorts specific axis of arr

two_d_arr.flatten() | Flattens 2D array two_d_arr to 1D

arr.T | Transposes arr (rows become columns and vice versa)

arr.reshape(3,4) | Reshapes arr to 3 rows, 4 columns without changing data

arr.resize((5,6)) | Changes arr shape to 5x6 and fills new values with 0

#### Adding/removing Elements

np.append(arr,values) | Appends values to end of arr

np.insert(arr,2,values) | Inserts values into arr before index 2

np.delete(arr,3,axis=0) | Deletes row on index 3 of arr

np.delete(arr,4,axis=1) | Deletes column on index 4 of arr

#### Combining/splitting

np.concatenate((arr1,arr2),axis=0) | Adds arr2 as rows to the end of arr1

np.concatenate((arr1,arr2),axis=1) | Adds arr2 as columns to end of arr1

np.split(arr,3) | Splits arr into 3 sub-arrays

np.hsplit(arr,5) | Splits arr horizontally on the 5th index

# Indexing/slicing/subsetting

arr[5] | Returns the element at index 5

arr[2,5] | Returns the 2D array element on index [2][5]

arr[1]=4 | Assigns array element on index 1 the value 4

arr[1,3]=10 | Assigns array element on index [1][3] the value 10

arr[0:3] | Returns the elements at indices 0,1,2 (On a 2D array: returns rows 0,1,2)

arr[0:3,4] | Returns the elements on rows 0,1,2 at column 4

arr[:2] | Returns the elements at indices 0,1 (On a 2D array: returns rows 0,1)

arr[:,1] | Returns the elements at index 1 on all rows

arr<5 | Returns an array with boolean values
(arr1<3) & (arr2>5) | Returns an array with boolean values

~arr | Inverts a boolean array

arr[arr<5] | Returns array elements smaller than 5

# Scalar Math

np.add(arr,1) | Add 1 to each array element

np.subtract(arr,2) | Subtract 2 from each array element

np.multiply(arr,3) | Multiply each array element by 3

np.divide(arr,4) | Divide each array element by 4 (returns np.nan for division by zero)

np.power(arr,5) | Raise each array element to the 5th power

# Vector Math

np.add(arr1,arr2) | Elementwise add arr2 to arr1

np.subtract(arr1,arr2) | Elementwise subtract arr2 from arr1

np.multiply(arr1,arr2) | Elementwise multiply arr1 by arr2

np.divide(arr1,arr2) | Elementwise divide arr1 by arr2

np.power(arr1,arr2) | Elementwise raise arr1 raised to the power of arr2

np.array_equal(arr1,arr2) | Returns True if the arrays have the same elements and shape

np.sqrt(arr) | Square root of each element in the array

np.sin(arr) | Sine of each element in the array

np.log(arr) | Natural log of each element in the array

np.abs(arr) | Absolute value of each element in the array

np.ceil(arr) | Rounds up to the nearest int

np.floor(arr) | Rounds down to the nearest int

np.round(arr) | Rounds to the nearest int



# Statistics

np.mean(arr,axis=0) | Returns mean along specific axis # horizontal representation

arr.sum() | Returns sum of arr

arr.min() | Returns minimum value of arr

arr.max(axis=0) | Returns maximum value of specific axis

np.var(arr) | Returns the variance of array

np.std(arr,axis=1) | Returns the standard deviation of specific axis

arr.corrcoef() | Returns correlation coefficient of array

In [2]:
import numpy as np
#pip install numpy

## Creating Arrays

In [ ]:
my_list = [0,1,2,3,4]
#dir(my_list)
type(my_list)

In [ ]:
arr = np.array(my_list)

In [ ]:
type(arr)

In [ ]:
arr=np.arange(0,10)## create an array with a range containing the lower and upper bound as mentioned
arr

In [5]:
np.arange(1,10,3) ## Print all  numbers with step size 3

array([1, 4, 7])

In [ ]:
np.zeros((5,5)) ## create a table with a dimension of 5*5 containing zeros

In [ ]:
np.ones((2,4)) ## create a table with a dimension of 2*4 [2 rows and 4 columns] with ones

In [7]:
np.random.rand(2,100) ## generate a random integer between 0-1

array([[0.42898384, 0.90685469, 0.68350372, 0.70088964, 0.98928258,
        0.13914739, 0.72208203, 0.103993  , 0.45266851, 0.40912292,
        0.78411895, 0.11730678, 0.22944222, 0.33302463, 0.62294515,
        0.16193552, 0.89829681, 0.0173574 , 0.85432615, 0.67827564,
        0.84025906, 0.2083101 , 0.43350904, 0.53957473, 0.89131421,
        0.02451653, 0.39005619, 0.3576378 , 0.99231889, 0.134943  ,
        0.61898677, 0.66725086, 0.73606281, 0.67187108, 0.03902272,
        0.09118   , 0.01910867, 0.22567499, 0.63114391, 0.60450913,
        0.05436836, 0.88765665, 0.60901903, 0.11998026, 0.5545504 ,
        0.61204867, 0.72329903, 0.60536952, 0.74887853, 0.45329256,
        0.23043667, 0.18814882, 0.67743418, 0.16101987, 0.89285413,
        0.22767707, 0.78259278, 0.73861698, 0.24860081, 0.34233168,
        0.10408033, 0.35655336, 0.39201435, 0.15290557, 0.24600582,
        0.29948745, 0.40228475, 0.34780055, 0.56651282, 0.52043064,
        0.5444996 , 0.59656917, 0.55709965, 0.86

In [3]:
np.random.randint(0,10,(3,3)) ## create random integers between 0-10 and form 3*3 matrix

array([[9, 7, 8],
       [8, 5, 5],
       [3, 2, 1]])

In [ ]:
np.linspace(0,100,10) ## create 10 values between 0-100 which are equally spaced

In [ ]:
np.linspace(0,10,101) ## create 101 values between 0-100 and are equally spaced

## Operations

In [ ]:
np.random.seed(1)  ## same random data
arr = np.random.randint(0,100,10) ## 10 random points between 0-100
arr

In [ ]:
arr2 = np.random.randint(0,100,10)
arr2

In [ ]:
arr = np.array(my_list)
arr

In [ ]:
arr.max()

In [ ]:
dir(arr)

In [ ]:
arr.min()

In [ ]:
arr.mean()

In [ ]:
arr.argmin() ## index of minimum value in the array

In [ ]:
arr.argmax() ## index of maximum value in the array

In [ ]:
arr2.reshape(5,2)# check with different values

## Indexing

In [ ]:
mat = np.arange(0,100).reshape(10,10)
print(mat)

In [ ]:
row = 6
col = 3
print(mat[row,:col]) ## Starting from 0. Only print the particular row. Print 6th row. Index=5

In [ ]:
print("\n")
print(mat[:2]) ## Print all the subset of matrix

In [ ]:
print(mat[1:3])

In [ ]:
print(mat[1:3])

In [ ]:
mat1=mat[:,1] ## 4th column
mat2=mat[:,2] ## 3rd column
print(mat1)
print("\n")
print(mat2)

In [ ]:
print(mat[1,:3])

In [ ]:
## concat matrix
mat3=np.concatenate((mat1,mat2))
print(mat3)

In [ ]:
## Reshape matrix
mat3=mat3.reshape(5,10)
print(mat3)

In [ ]:
row = 4
col = 4
mat3[row,col] 

row1=4
col1=4
mat3[row1,col1]

In [ ]:
# With Slices
mat3[:,col]

## Masking

In [ ]:
mat > 50

In [ ]:
mat[mat>49].reshape(10,5)

In [ ]:
arr=mat[mat>49]
arr

In [ ]:
arr.reshape(10,5)
