In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
my_list = [1,2,3]
my_list

In [ ]:
np.array(my_list) ## Cast List an numpy array

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] ## 2 dimensional Array. "[[" : 2 brackets indicate that
my_matrix

In [ ]:
np.array(my_matrix)

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,11,2) ## Arrange till 11 (excluding) with an interval of 3

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.arange(0,11,3)


array([0, 3, 6, 9])

### zeros and ones

Generate arrays of zeros or ones

In [21]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [22]:
np.zeros((5,5)) ## Create a 5*5 matrix with zero's

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [23]:
np.ones(3) ## Create a 3*1 matrix with one's

array([ 1.,  1.,  1.])

In [30]:
np.ones((3,3))## Create a 3*3 matrix with ones



array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [40]:
np.linspace(0,10,4) ## Divide 10 by 3

array([  0.        ,   3.33333333,   6.66666667,  10.        ])

In [39]:
np.linspace(0,50,5) ## Divide 50 by 4

array([  0. ,  12.5,  25. ,  37.5,  50. ])

## eye

Creates an identity matrix

In [42]:
np.eye(3) ## #3*3 2D Matrix with 1 as diagonal

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [43]:
np.random.rand(2)

array([ 0.7271799 ,  0.71600141])

In [44]:
np.random.rand(5,5)

array([[ 0.46329107,  0.67530974,  0.60551787,  0.62089746,  0.13208746],
       [ 0.81117459,  0.98584715,  0.97582862,  0.65244817,  0.78334104],
       [ 0.50420774,  0.72272924,  0.48218177,  0.83293624,  0.22806247],
       [ 0.6504849 ,  0.17296532,  0.45795423,  0.19403984,  0.698112  ],
       [ 0.61256669,  0.72088712,  0.99160154,  0.59177965,  0.29850228]])

### randn

Return a sample (or samples) from the "standard normal" distribution (Centred around 0). Unlike rand this is uniform:

In [48]:
np.random.randn(5)

array([-0.48991458,  1.75145993, -0.74565783, -1.36564038,  0.33234702])

In [46]:
np.random.randn(5,5)

array([[-0.55932031, -0.65228105,  1.43832171, -0.39958986,  0.61013176],
       [ 0.26939986, -0.57020463, -1.92992971, -0.7817175 ,  0.85258353],
       [-0.39379147, -0.21649156, -1.4209486 , -1.99097593,  0.51884895],
       [ 0.59693513,  1.3297477 , -0.95199793, -2.37778329, -0.83786596],
       [ 0.31932268,  0.26996271,  1.2060813 ,  1.65862918, -0.89197707]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [51]:
np.random.randint(1,100)## Generate 1 integer between 1 and 99

16

In [50]:
np.random.randint(1,100,10)## Generate 10 integers between 1 and 99

array([97, 16, 25, 65, 33, 34, 21, 91, 98, 82])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [71]:
arr = np.arange(25) ## Create an array of 25 integers starting from 0
ranarr = np.random.randint(0,50,10) ## Create 10 integers from 0 to 49 (exclusive)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
ranarr

array([13,  3, 18, 12, 28,  1, 40, 26,  1, 25])

## Reshape
Returns an array containing the same data with a new shape.

In [73]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
ranarr.reshape(5,2)

array([[14, 24],
       [22, 16],
       [10, 39],
       [ 9,  0],
       [30, 46]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [58]:
ranarr

array([13,  3, 18, 12, 28,  1, 40, 26,  1, 25])

In [59]:
ranarr.max()

40

In [60]:
ranarr.argmax()

6

In [61]:
ranarr.min()

1

In [62]:
ranarr.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):

In [103]:
# Vector
arr=np.arange(1,10)
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
arr.shape ## 1 dimensional array

(9,)

In [106]:
# Notice the two sets of brackets
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [90]:
arr.reshape(1,9).shape

(1, 9)

In [95]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [92]:
arr.reshape(9,1).shape

(9, 1)

### dtype

You can also grab the data type of the object in the array:

In [93]:
arr.dtype

dtype('int32')